(deftheme pk "Created 2013-06-01.")

(custom-theme-set-variables 'pk)

(custom-theme-set-faces
 'pk
 '(cursor ((t (:background "gray100" :foreground "#ffffff"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#cc8c3c"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#cc8c3c"))))
 '(font-lock-doc-face ((t (:foreground "green1"))))
 '(font-lock-doc-string-face ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(font-lock-string-face ((t (:foreground "green"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#ffdd33" :bold t))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(magit-diff-add ((t (:foreground "gray90"))))
 '(ruby-op-face ((t (:foreground "gray98" :weight bold))))
 '(magit-branch ((t nil)))
 '(font-lock-function-name-face ((t (:foreground "medium purple"))))
 '(font-lock-variable-name-face ((t (:foreground "gray76"))))
 '(font-lock-preprocessor-face ((t (:foreground "dark cyan"))))
 '(font-lock-constant-face ((t (:foreground "maroon1"))))
 '(font-lock-type-face ((t (:foreground "cornflower blue"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#f43841"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "#95a99f"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "black" :background "#f43841"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#96a6c8" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#9e95c7" :underline t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "black" :background "#f5f5f5"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#f4f4ff" :background "#5f627f"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "black" :background "#f43841"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#111" :foreground "#444"))))
 '(border ((((class color) (min-colors 89)) (:background "#111" :foreground "#444"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#453d41" :foreground "white"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:background "#453d41" :foreground "white"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#453d41" :foreground "#999"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#96a6c8"))))
 '(region ((((class color) (min-colors 89)) (:background "#484848"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#484848" :foreground "#f4f4ff"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#52494e" :foreground "white"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#52494e" :foreground "#f4f4ff"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#f4f4ff" :background "#c73c3f"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#282828" :foreground nil))))
 '(highlight-current-line-face ((((class color) (min-colors 89)) (:background "#282828" :foreground nil))))
 '(holiday-face ((((class color) (min-colors 89)) (:foreground "#f43841"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "#96a6c8"))))
 '(info-visited ((((class color) (min-colors 89)) (:foreground "#9e95c7"))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:foreground "#96a6c8" :bold t))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:foreground "#95a99f" :bold t))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:foreground "#95a99f" :italic t))))
 '(font-latex-math-face ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(font-latex-warning-face ((((class color) (min-colors 89)) (:foreground "#f43841"))))
 '(font-latex-slide-title-face ((((class color) (min-colors 89)) (:foreground "#96a6c8"))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) (:foreground "#96a6c8"))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(eshell-ls-backup ((((class color) (min-colors 89)) (:foreground "#95a99f"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#96a6c8" :weight bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:foreground "#95a99f" :inherit nil))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#73c936" :bold nil))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#96a6c8" :weight bold))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#73c936" :inherit nil))))
 '(egg-text-base ((((class color) (min-colors 89)) (:foreground "#e4e4ef"))))
 '(egg-help-header-1 ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(egg-help-header-2 ((((class color) (min-colors 89)) (:foreground "#96a6c8"))))
 '(egg-branch ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(egg-branch-mono ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(egg-term ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(egg-diff-add ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(egg-diff-del ((((class color) (min-colors 89)) (:foreground "#f43841"))))
 '(egg-diff-file-header ((((class color) (min-colors 89)) (:foreground "#9e95c7"))))
 '(egg-section-title ((((class color) (min-colors 89)) (:foreground "#ffdd33"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#73c936"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#181818")))))

(provide-theme 'pk)
(provide 'pk-theme)
